# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 491b2af4474afa8880780a045c71963157a2a4dcf097a409d3bdae57618e8c539add3004f049e8c6cdea5d32b0e716bf8b9a33f171f7a738e39b235bb2d1f562

test:
  secret_key_base: 6f4c7219e09f5d60b1fb858dcdc20467a506194edd71d97bf3aa88fade09a9424af8c0ee9c3cf81703273a5c9ec6a4689fcf5d6a5018a34a84cdfd61728baae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
